<script language="JavaScript"><!--
var                             tosWin='toolbar=0,directories=0,fullscreen=0,menubar=0,scrollbars=1,resizable=1,width=550,height=350,top=50,left=50';
var tosWindow = null;
function opentWin(page2open)
{
 if(tosWindow != null) if(!tosWindow.closed) 
                            tosWindow.close()
 tosWindow=open(page2open,'tosWin', tosWin); 
}
//-->
</script>
</FONT>